/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;


import BLL.ChuyenDoi;
import BLL.Excel;
import static DAO.DAOSanPham.ImagePast;
import static DAO.DAOSanPham.ResizeImage;
import DTO.DTONhaCungCap;
import static GUI.pnlthemnhacungcap.btnthem;
import static GUI.pnlthemnhacungcap.txtMancc;
import net.connectcode.Code128Auto;
import java.util.Random;
import DTO.MyCombobox;
import java.awt.Component;
import java.awt.Image;
import java.io.File;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultCellEditor;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author Takemikazuchi
 */
public class pnlsanpham extends javax.swing.JPanel {

    /**
     *
     */
    public pnlsanpham() {
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {

        }
        initComponents();
        run();

        Date currenTime = new Date();
        jdcNgayTao.setDate(currenTime);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTenAnh = new javax.swing.JLabel();
        lblLink = new javax.swing.JLabel();
        txtidsanpham = new javax.swing.JTextField();
        jPanel87 = new javax.swing.JPanel();
        jPanel41 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        txtIDSanPham = new javax.swing.JTextField();
        tbpchuyentab = new javax.swing.JTabbedPane();
        pnldanhsach = new javax.swing.JPanel();
        srcdanhsach = new javax.swing.JScrollPane();
        tblSanPham = new javax.swing.JTable();
        txttimkiem = new javax.swing.JTextField();
        jPanel21 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel45 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtMoTa = new javax.swing.JTextArea();
        jPanel58 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        cbkke = new javax.swing.JCheckBox();
        cbbViTriKe = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        lbthongtincoban1 = new javax.swing.JLabel();
        jPanel30 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        cbbThuocTinhKhachHang = new javax.swing.JComboBox<>();
        jPanel32 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jdcNgayTao = new com.toedter.calendar.JDateChooser();
        jPanel34 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtTenSanPham = new javax.swing.JTextField();
        jPanel40 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel33 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtDonViTinh = new javax.swing.JTextField();
        jPanel35 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        cbbHangSanPham = new javax.swing.JComboBox<>();
        jPanel39 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        cbbLoaiSanPham = new javax.swing.JComboBox<>();
        jPanel11 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel43 = new javax.swing.JPanel();
        bttLamMoi = new javax.swing.JButton();
        bttThem = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        jScrollPaneSanPham = new javax.swing.JScrollPane();
        tblThemThuocTinh = new javax.swing.JTable();
        jPanel17 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        bttLamMoiThuocTinh = new javax.swing.JButton();
        bttXoaThuocTinh = new javax.swing.JButton();
        bttThemThuocTinh = new javax.swing.JButton();
        jPanel42 = new javax.swing.JPanel();
        bttZoomTable = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel36 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        lblNull = new javax.swing.JLabel();
        jPanel37 = new javax.swing.JPanel();
        srcdanhsach2 = new javax.swing.JScrollPane();
        tblKho = new javax.swing.JTable();
        txtTimKiemKho = new javax.swing.JTextField();
        jPanel38 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        btnTimKiem = new javax.swing.JButton();

        lblTenAnh.setText("jLabel4");

        lblLink.setText("jLabel4");
        lblLink.setEnabled(false);

        jPanel87.setToolTipText("sadsad");

        javax.swing.GroupLayout jPanel87Layout = new javax.swing.GroupLayout(jPanel87);
        jPanel87.setLayout(jPanel87Layout);
        jPanel87Layout.setHorizontalGroup(
            jPanel87Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 975, Short.MAX_VALUE)
        );
        jPanel87Layout.setVerticalGroup(
            jPanel87Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 612, Short.MAX_VALUE)
        );

        jPanel41.setBackground(new java.awt.Color(255, 255, 255));
        jPanel41.setLayout(new java.awt.BorderLayout());

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("ID sản phẩm");
        jLabel19.setPreferredSize(new java.awt.Dimension(75, 20));
        jPanel41.add(jLabel19, java.awt.BorderLayout.PAGE_START);

        txtIDSanPham.setEditable(false);
        jPanel41.add(txtIDSanPham, java.awt.BorderLayout.CENTER);

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(980, 619));
        setRequestFocusEnabled(false);
        setVerifyInputWhenFocusTarget(false);

        tbpchuyentab.setBackground(new java.awt.Color(255, 255, 255));
        tbpchuyentab.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        tbpchuyentab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbpchuyentabMouseClicked(evt);
            }
        });

        pnldanhsach.setBackground(new java.awt.Color(33, 36, 51));
        pnldanhsach.setPreferredSize(new java.awt.Dimension(980, 618));

        tblSanPham.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tblSanPham.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        tblSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Loại", "Nhãn hiệu", "Giá bán", "Giá nhập", "Ngày nhập", "Tồn kho", "Size", "Màu", "Vị trí(Kệ)", "Id Sản phẩm", "Ảnh Sản Phẩm", "Mã Quét"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSanPham.setDragEnabled(true);
        tblSanPham.setFocusable(false);
        tblSanPham.setIntercellSpacing(new java.awt.Dimension(0, 1));
        tblSanPham.setName(""); // NOI18N
        tblSanPham.setRowHeight(55);
        tblSanPham.setSelectionBackground(new java.awt.Color(204, 204, 204));
        tblSanPham.setShowVerticalLines(false);
        tblSanPham.getTableHeader().setReorderingAllowed(false);
        tblSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSanPhamMouseClicked(evt);
            }
        });
        srcdanhsach.setViewportView(tblSanPham);

        txttimkiem.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txttimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttimkiemActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/below_15px.png"))); // NOI18N
        jButton1.setText("  Xuất File Excel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Xóa sản phẩm");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setText("Làm mới");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2)
                    .addComponent(jButton4))
                .addContainerGap())
        );

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/filter_edit_20px.png"))); // NOI18N
        jButton5.setText("Lọc sản phẩm");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton3.setText("Tìm kiếm");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnldanhsachLayout = new javax.swing.GroupLayout(pnldanhsach);
        pnldanhsach.setLayout(pnldanhsachLayout);
        pnldanhsachLayout.setHorizontalGroup(
            pnldanhsachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnldanhsachLayout.createSequentialGroup()
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txttimkiem)
                .addGap(0, 0, 0)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(srcdanhsach, javax.swing.GroupLayout.DEFAULT_SIZE, 975, Short.MAX_VALUE)
            .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnldanhsachLayout.setVerticalGroup(
            pnldanhsachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnldanhsachLayout.createSequentialGroup()
                .addGroup(pnldanhsachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(srcdanhsach, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tbpchuyentab.addTab("Danh sách sản phẩm", new javax.swing.ImageIcon(getClass().getResource("/IMAGE/list_20px.png")), pnldanhsach); // NOI18N

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(244, 246, 248), 5));
        jPanel4.setPreferredSize(new java.awt.Dimension(275, 550));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.setLayout(new java.awt.BorderLayout());

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        jPanel13.setLayout(new java.awt.BorderLayout());

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));
        jPanel18.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Thông tin khác");
        jLabel2.setPreferredSize(new java.awt.Dimension(34, 20));

        jPanel45.setBackground(new java.awt.Color(255, 255, 255));
        jPanel45.setLayout(new java.awt.BorderLayout());

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Mô tả");
        jLabel23.setPreferredSize(new java.awt.Dimension(75, 20));
        jPanel45.add(jLabel23, java.awt.BorderLayout.PAGE_START);

        txtMoTa.setColumns(20);
        txtMoTa.setRows(5);
        jScrollPane3.setViewportView(txtMoTa);

        jPanel45.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jPanel58.setBackground(new java.awt.Color(255, 255, 255));
        jPanel58.setLayout(new java.awt.BorderLayout());

        jLabel27.setBackground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Ví trị kệ");
        jLabel27.setPreferredSize(new java.awt.Dimension(106, 20));
        jPanel58.add(jLabel27, java.awt.BorderLayout.PAGE_START);

        cbkke.setBackground(new java.awt.Color(51, 51, 51));
        cbkke.setForeground(new java.awt.Color(255, 255, 255));
        cbkke.setText("Đặt vị trí");
        cbkke.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cbkke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbkkeActionPerformed(evt);
            }
        });
        jPanel58.add(cbkke, java.awt.BorderLayout.LINE_END);

        jPanel58.add(cbbViTriKe, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel45, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                    .addComponent(jPanel58, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel58, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel45, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel13.add(jPanel18, java.awt.BorderLayout.CENTER);

        jPanel7.add(jPanel13, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel7, java.awt.BorderLayout.CENTER);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(244, 246, 248), 5));
        jPanel5.setPreferredSize(new java.awt.Dimension(700, 550));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        jPanel6.setLayout(new java.awt.BorderLayout());

        jPanel26.setBackground(new java.awt.Color(255, 255, 255));
        jPanel26.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbthongtincoban1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lbthongtincoban1.setText("Thông tin cơ bản sản phẩm");

        jPanel30.setBackground(new java.awt.Color(255, 255, 255));
        jPanel30.setLayout(new java.awt.BorderLayout());

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Đối tượng");
        jLabel9.setPreferredSize(new java.awt.Dimension(52, 20));
        jPanel30.add(jLabel9, java.awt.BorderLayout.PAGE_START);

        cbbThuocTinhKhachHang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ", "Cả hai" }));
        jPanel30.add(cbbThuocTinhKhachHang, java.awt.BorderLayout.CENTER);

        jPanel32.setBackground(new java.awt.Color(255, 255, 255));
        jPanel32.setLayout(new java.awt.BorderLayout());

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Ngày tạo");
        jLabel10.setPreferredSize(new java.awt.Dimension(31, 20));
        jPanel32.add(jLabel10, java.awt.BorderLayout.PAGE_START);
        jPanel32.add(jdcNgayTao, java.awt.BorderLayout.CENTER);

        jPanel34.setBackground(new java.awt.Color(255, 255, 255));
        jPanel34.setLayout(new java.awt.BorderLayout());

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Tên sản phẩm");
        jLabel12.setPreferredSize(new java.awt.Dimension(106, 20));
        jPanel34.add(jLabel12, java.awt.BorderLayout.PAGE_START);
        jPanel34.add(txtTenSanPham, java.awt.BorderLayout.CENTER);

        jPanel40.setBackground(new java.awt.Color(255, 255, 255));
        jPanel40.setLayout(new java.awt.BorderLayout());

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("jLabel5");

        jPanel33.setBackground(new java.awt.Color(255, 255, 255));
        jPanel33.setLayout(new java.awt.BorderLayout());

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Đơn vị tính");
        jLabel11.setPreferredSize(new java.awt.Dimension(52, 20));
        jPanel33.add(jLabel11, java.awt.BorderLayout.PAGE_START);
        jPanel33.add(txtDonViTinh, java.awt.BorderLayout.CENTER);

        jPanel35.setBackground(new java.awt.Color(255, 255, 255));
        jPanel35.setLayout(new java.awt.BorderLayout());

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Hãng sản phẩm");
        jLabel13.setPreferredSize(new java.awt.Dimension(52, 20));
        jPanel35.add(jLabel13, java.awt.BorderLayout.PAGE_START);

        jPanel35.add(cbbHangSanPham, java.awt.BorderLayout.CENTER);

        jPanel39.setBackground(new java.awt.Color(255, 255, 255));
        jPanel39.setLayout(new java.awt.BorderLayout());

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Loại sản phẩm");
        jLabel14.setPreferredSize(new java.awt.Dimension(106, 20));
        jPanel39.add(jLabel14, java.awt.BorderLayout.PAGE_START);

        jPanel39.add(cbbLoaiSanPham, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel26Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(308, 308, 308))
                    .addComponent(jPanel40, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel26Layout.createSequentialGroup()
                        .addComponent(jPanel34, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                        .addGap(17, 17, 17)
                        .addComponent(jPanel30, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE))
                    .addComponent(lbthongtincoban1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel26Layout.createSequentialGroup()
                        .addComponent(jPanel32, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                        .addGap(16, 16, 16)
                        .addComponent(jPanel33, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE))
                    .addGroup(jPanel26Layout.createSequentialGroup()
                        .addComponent(jPanel39, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                        .addGap(17, 17, 17)
                        .addComponent(jPanel35, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lbthongtincoban1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel34, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(jPanel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel32, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(jPanel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel39, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(jPanel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel40, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.add(jPanel26, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel6, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel11.setPreferredSize(new java.awt.Dimension(975, 350));
        jPanel11.setLayout(new java.awt.BorderLayout());

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(244, 246, 248), 5));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        jPanel12.setLayout(new java.awt.BorderLayout());

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel14.setPreferredSize(new java.awt.Dimension(951, 40));
        jPanel14.setLayout(new javax.swing.BoxLayout(jPanel14, javax.swing.BoxLayout.LINE_AXIS));

        jPanel43.setBackground(new java.awt.Color(255, 255, 255));
        jPanel43.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        bttLamMoi.setText("Làm mới");
        bttLamMoi.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        bttLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttLamMoiActionPerformed(evt);
            }
        });

        bttThem.setText("Thêm");
        bttThem.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        bttThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttThemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel43Layout = new javax.swing.GroupLayout(jPanel43);
        jPanel43.setLayout(jPanel43Layout);
        jPanel43Layout.setHorizontalGroup(
            jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 943, Short.MAX_VALUE)
            .addGroup(jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel43Layout.createSequentialGroup()
                    .addContainerGap(609, Short.MAX_VALUE)
                    .addComponent(bttLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(bttThem, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        jPanel43Layout.setVerticalGroup(
            jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel43Layout.createSequentialGroup()
                    .addGap(1, 1, 1)
                    .addGroup(jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bttThem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bttLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel14.add(jPanel43);

        jPanel12.add(jPanel14, java.awt.BorderLayout.PAGE_END);

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel16.setLayout(new java.awt.BorderLayout());

        tblThemThuocTinh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Hình ảnh", "Tên Size", "Tên Màu", "Khối lượng", "Giá bán lẻ", "Giá bán buôn", "Giá nhập", "Mã sản phẩm", "Link"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblThemThuocTinh.setRowHeight(30);
        tblThemThuocTinh.setSelectionBackground(new java.awt.Color(51, 51, 51));
        tblThemThuocTinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblThemThuocTinhMouseClicked(evt);
            }
        });
        tblThemThuocTinh.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblThemThuocTinhKeyReleased(evt);
            }
        });
        jScrollPaneSanPham.setViewportView(tblThemThuocTinh);

        jPanel16.add(jScrollPaneSanPham, java.awt.BorderLayout.CENTER);

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel17.setPreferredSize(new java.awt.Dimension(947, 40));
        jPanel17.setLayout(new javax.swing.BoxLayout(jPanel17, javax.swing.BoxLayout.LINE_AXIS));

        jPanel25.setBackground(new java.awt.Color(255, 255, 255));
        jPanel25.setPreferredSize(new java.awt.Dimension(500, 44));

        bttLamMoiThuocTinh.setText("Làm mới toàn bộ");
        bttLamMoiThuocTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttLamMoiThuocTinhActionPerformed(evt);
            }
        });

        bttXoaThuocTinh.setText("Xóa thuộc tính");
        bttXoaThuocTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttXoaThuocTinhActionPerformed(evt);
            }
        });

        bttThemThuocTinh.setText("Thêm Size - Màu sản phẩm");
        bttThemThuocTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttThemThuocTinhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 521, Short.MAX_VALUE)
            .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel25Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(bttThemThuocTinh)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(bttXoaThuocTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(bttLamMoiThuocTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
            .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel25Layout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(bttLamMoiThuocTinh, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                        .addComponent(bttXoaThuocTinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bttThemThuocTinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel17.add(jPanel25);

        jPanel42.setBackground(new java.awt.Color(255, 255, 255));
        jPanel42.setPreferredSize(new java.awt.Dimension(400, 40));

        bttZoomTable.setText("Phóng to bảng");
        bttZoomTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttZoomTableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel42Layout = new javax.swing.GroupLayout(jPanel42);
        jPanel42.setLayout(jPanel42Layout);
        jPanel42Layout.setHorizontalGroup(
            jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 422, Short.MAX_VALUE)
            .addGroup(jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel42Layout.createSequentialGroup()
                    .addContainerGap(421, Short.MAX_VALUE)
                    .addComponent(bttZoomTable, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        jPanel42Layout.setVerticalGroup(
            jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
            .addGroup(jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel42Layout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(bttZoomTable, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addGap(3, 3, 3)))
        );

        jPanel17.add(jPanel42);

        jPanel16.add(jPanel17, java.awt.BorderLayout.PAGE_END);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("  Thuộc tính sản phẩm");
        jLabel1.setPreferredSize(new java.awt.Dimension(133, 20));
        jPanel16.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel12.add(jPanel16, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel11.add(jPanel8, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tbpchuyentab.addTab("Thêm sản phẩm", new javax.swing.ImageIcon(getClass().getResource("/IMAGE/add_property_20px.png")), jPanel1); // NOI18N

        jPanel36.setBackground(new java.awt.Color(255, 255, 255));

        jPanel15.setLayout(new java.awt.BorderLayout());
        jPanel15.add(lblNull, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel36Layout = new javax.swing.GroupLayout(jPanel36);
        jPanel36.setLayout(jPanel36Layout);
        jPanel36Layout.setHorizontalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel36Layout.setVerticalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tbpchuyentab.addTab("Sửa sản phẩm", new javax.swing.ImageIcon(getClass().getResource("/IMAGE/maintenancde_20px.png")), jPanel36); // NOI18N

        tblKho.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tblKho.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        tblKho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", "", null, "", "", ""},
                {"", "", null, "", "", ""},
                {"", "", null, "", "", ""},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã Kho", "Tên Sản Phẩm", "Phiếu Nhập", "Tồn Kho", "Hàng Đang Về", "Trạng Thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblKho.setDragEnabled(true);
        tblKho.setFocusable(false);
        tblKho.setName(""); // NOI18N
        tblKho.setRowHeight(40);
        tblKho.setSelectionBackground(new java.awt.Color(204, 204, 204));
        tblKho.setShowVerticalLines(false);
        tblKho.getTableHeader().setReorderingAllowed(false);
        srcdanhsach2.setViewportView(tblKho);

        txtTimKiemKho.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel38Layout = new javax.swing.GroupLayout(jPanel38);
        jPanel38.setLayout(jPanel38Layout);
        jPanel38Layout.setHorizontalGroup(
            jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel38Layout.setVerticalGroup(
            jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/filter_edit_20px.png"))); // NOI18N
        jButton9.setText("Lọc kho");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel37Layout = new javax.swing.GroupLayout(jPanel37);
        jPanel37.setLayout(jPanel37Layout);
        jPanel37Layout.setHorizontalGroup(
            jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel37Layout.createSequentialGroup()
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTimKiemKho, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTimKiem)
                .addGap(9, 9, 9))
            .addComponent(srcdanhsach2)
            .addComponent(jPanel38, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel37Layout.setVerticalGroup(
            jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel37Layout.createSequentialGroup()
                .addGroup(jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTimKiemKho, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(srcdanhsach2, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tbpchuyentab.addTab("Quản lý kho", new javax.swing.ImageIcon(getClass().getResource("/IMAGE/warehouse_20px.png")), jPanel37); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbpchuyentab, javax.swing.GroupLayout.DEFAULT_SIZE, 980, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbpchuyentab, javax.swing.GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jdllocloaisanpham lsp = new jdllocloaisanpham(new javax.swing.JFrame(), true);
        lsp.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    public static JComboBox cbbsize = new JComboBox();
    public static JComboBox cbbmau = new JComboBox();

    public void run() {
        
       
        BLL.BLLSanPham.HienThiSanPham(tblSanPham);
        BLL.BLLSanPham.DoDuLieucbbKeSanPham(cbbViTriKe);
        BLL.BLLSanPham.DoDuLieucbbHangSanPham(cbbHangSanPham);
        BLL.BLLSanPham.DoDuLieucbbLoaiSanPham(cbbLoaiSanPham);
        BLL.BLLSanPham.DoDuLieucbbSizeSanPham(cbbsize);
        BLL.BLLSanPham.DoDuLieucbbMauSanPham(cbbmau);
     
        BLL.BLLKho.HienThiKho(tblKho, txtTimKiemKho.getText());
       
        tblThemThuocTinh.setRowHeight(54);
        tblThemThuocTinh.getColumnModel().getColumn(0).setPreferredWidth(54);
         tblThemThuocTinh.getColumnModel().getColumn(8).setWidth(0);
        tblThemThuocTinh.getColumnModel().getColumn(8).setMinWidth(0);
        tblThemThuocTinh.getColumnModel().getColumn(8).setMaxWidth(0); 
        cbbViTriKe.setEnabled(false);

    }
    private void tbpchuyentabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbpchuyentabMouseClicked

    }//GEN-LAST:event_tbpchuyentabMouseClicked

    public void lammoi() {
        txtTenSanPham.setText(null);
      
        txtDonViTinh.setText(null);
        txtMoTa.setText(null);
        cbbThuocTinhKhachHang.setSelectedIndex(0);
        cbbLoaiSanPham.setSelectedIndex(0);
        cbbViTriKe.setSelectedIndex(0);
        cbbHangSanPham.setSelectedIndex(0);
    
        lblTenAnh.setText("selectimage.jpg");
        Date currenTime = new Date();
        jdcNgayTao.setDate(currenTime);
        jButton1.setEnabled(true);
        DefaultTableModel dtm = (DefaultTableModel) tblThemThuocTinh.getModel();
        dtm.setRowCount(0);

    }
    private void tblSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSanPhamMouseClicked

        if (evt.getClickCount() == 2) {
            int soDongDuocChon = tblSanPham.getSelectedRowCount();
            if (soDongDuocChon == 1) {

                lblNull.setVisible(false);
                jPanel15.removeAll();
                pnlthongtinsanpham nnn = new pnlthongtinsanpham();
                jPanel15.add(nnn);
                tbpchuyentab.setSelectedIndex(2);

                int dongDuocChon = tblSanPham.getSelectedRow();
                try {
                    ResultSet rs = DAO.DAOSanPham.LaySanPhamTheoId(tblSanPham.getValueAt(dongDuocChon, 11).toString());
                    if (rs.next()) {

                        GUI.pnlthongtinsanpham.txtTensanpham.setText(rs.getString("tensanpham"));
                        GUI.pnlthongtinsanpham.txtDonvi.setText(rs.getString("donvitinh"));
                        GUI.pnlthongtinsanpham.txtGiabanbuon.setText(rs.getString("giabanbuon"));
                        GUI.pnlthongtinsanpham.txtGiabanle.setText(rs.getString("giabanle"));
                        GUI.pnlthongtinsanpham.txtGiavon.setText(rs.getString("gianhap"));
                        GUI.pnlthongtinsanpham.txtKhoiluong.setText(rs.getString("khoiluong"));
                        GUI.pnlthongtinsanpham.txtMota.setText(rs.getString("motasanpham"));
                        GUI.pnlthongtinsanpham.cbbThuoctinhkhachhang.setSelectedItem(rs.getString("thuoctinhkhachhang"));
                        GUI.pnlthongtinsanpham.txtSoluong.setText(rs.getString("tonkho"));
                        GUI.pnlthongtinsanpham.txtMasanpham.setText(rs.getString("masanpham"));
                        GUI.pnlthongtinsanpham.jdcNgaytao.setDate(rs.getDate("ngaytao"));
                        GUI.pnlthongtinsanpham.txtIdsanpham.setText(rs.getString("idsanpham"));

                        ResultSet rsHang = DAO.DAOHangSanPham.LayHangSanPhamTheoid(rs.getString("idhangsanpham"));
                        try {
                            while (rsHang.next()) {
                                DefaultComboBoxModel cbbModel1 = (DefaultComboBoxModel) GUI.pnlthongtinsanpham.cbbHangsanpham.getModel();
                                for (int i = 0; i < GUI.pnlthongtinsanpham.cbbHangsanpham.getItemCount(); i++) {
                                    MyCombobox mb1 = (MyCombobox) cbbModel1.getElementAt(i);
                                    String tenCV = mb1.Text.toString();
                                    if (tenCV.equals(rsHang.getString("tenhang"))) {
                                        GUI.pnlthongtinsanpham.cbbHangsanpham.setSelectedIndex(i);
                                    }
                                }
                            }
                        } catch (SQLException ex) {
                            ThongBaoLoi.ThongBao("Lỗi Lấy dữ liệu ComboBox Hãng sản phẩm", "Thông Báo");
                        }
                        //Đổ vào cbb Size
                        ResultSet rsSize = DAO.DAOSize.LaySizeSanPhamTheoID(rs.getString("idsizesanpham"));
                        try {
                            while (rsSize.next()) {
                                DefaultComboBoxModel cbbModel1 = (DefaultComboBoxModel) GUI.pnlthongtinsanpham.cbbSize.getModel();
                                for (int i = 0; i < GUI.pnlthongtinsanpham.cbbSize.getItemCount(); i++) {
                                    MyCombobox mb1 = (MyCombobox) cbbModel1.getElementAt(i);
                                    String tenCV = mb1.Text.toString();
                                    if (tenCV.equals(rsSize.getString("tensize"))) {
                                        GUI.pnlthongtinsanpham.cbbSize.setSelectedIndex(i);
                                    }
                                }
                            }
                        } catch (SQLException ex) {
                            ThongBaoLoi.ThongBao("Lỗi Lấy dữ liệu ComboBox Size sản phẩm", "Thông Báo");

                        }

                        ResultSet rsMau = DAO.DAOMauSanPham.LayMauSanPhamTheoID(rs.getString("idmausanpham"));
                        try {
                            while (rsMau.next()) {
                                DefaultComboBoxModel cbbModel1 = (DefaultComboBoxModel) GUI.pnlthongtinsanpham.cbbMau.getModel();
                                for (int i = 0; i < GUI.pnlthongtinsanpham.cbbMau.getItemCount(); i++) {
                                    MyCombobox mb1 = (MyCombobox) cbbModel1.getElementAt(i);
                                    String tenCV = mb1.Text.toString();
                                    if (tenCV.equals(rsMau.getString("tenmausanpham"))) {
                                        GUI.pnlthongtinsanpham.cbbMau.setSelectedIndex(i);
                                    }
                                }
                            }
                        } catch (SQLException ex) {
                            ThongBaoLoi.ThongBao("Lỗi Lấy dữ liệu ComboBox màu sản phẩm", "Thông Báo");
                        }
                        //Đổ dữ liệu cbb Loại sản phẩm
                        ResultSet rsLoai = DAO.DAOLoaiSanPham.LayLoaiSanPhamTheoID(rs.getString("idloaisanpham"));
                        try {
                            while (rsLoai.next()) {
                                DefaultComboBoxModel cbbModel1 = (DefaultComboBoxModel) GUI.pnlthongtinsanpham.cbbLoaisanpham.getModel();
                                for (int i = 0; i < GUI.pnlthongtinsanpham.cbbLoaisanpham.getItemCount(); i++) {
                                    MyCombobox mb1 = (MyCombobox) cbbModel1.getElementAt(i);
                                    String tenCV = mb1.Text.toString();
                                    if (tenCV.equals(rsLoai.getString("tenloaisanpham"))) {
                                        GUI.pnlthongtinsanpham.cbbLoaisanpham.setSelectedIndex(i);
                                    }
                                }
                            }
                        } catch (SQLException ex) {
                            ThongBaoLoi.ThongBao("Lỗi Lấy dữ liệu ComboBox Loại sản phẩm", "Thông Báo");
                        }
                        //Đổ vào cbb kệ
                        ResultSet rsKe = DAO.DAOKe.LayKeTheoID(rs.getString("idke"));
                        try {
                            while (rsKe.next()) {
                                DefaultComboBoxModel cbbModel1 = (DefaultComboBoxModel) GUI.pnlthongtinsanpham.cbbVitrike.getModel();
                                for (int i = 0; i < GUI.pnlthongtinsanpham.cbbVitrike.getItemCount(); i++) {
                                    MyCombobox mb1 = (MyCombobox) cbbModel1.getElementAt(i);
                                    String tenCV = mb1.Text.toString();
                                    if (tenCV.equals(rsKe.getString("tenke"))) {
                                        GUI.pnlthongtinsanpham.cbbVitrike.setSelectedIndex(i);
                                    }
                                }
                            }
                        } catch (SQLException ex) {
                            ThongBaoLoi.ThongBao("Lỗi Lấy dữ liệu ComboBox Kệ sản phẩm", "Thông Báo");

                        }

                        ImageIcon imageIcon = new ImageIcon(new ImageIcon(rs.getBytes("anhsanpham")).getImage().getScaledInstance(190, 190, Image.SCALE_SMOOTH));
                        GUI.pnlthongtinsanpham.lblAnhsanpham.setIcon(imageIcon);

                    }
                } catch (SQLException ex) {
                    Logger.getLogger(pnlsanpham.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        }
               int col = pnlsanpham.tblSanPham.columnAtPoint(evt.getPoint());
            if (col == 13)
            {
             jdlShowBarcode qr = new jdlShowBarcode(new javax.swing.JFrame(), true);
             qr.setVisible(true);
             
            }  

    }//GEN-LAST:event_tblSanPhamMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Excel excel = new Excel();
        if (excel.ExportExcel(tblSanPham)) {
            ThongBaoThongTin.ThongBao("Xuất File Excel thành công!", "Thông báo");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int cacDong[] = tblSanPham.getSelectedRows();
        for (int i = 0; i < cacDong.length; i++) {
            int XoaSize = Integer.parseInt(tblSanPham.getValueAt(cacDong[i], 11).toString());
            DAO.DAOSanPham.XoaSP(XoaSize);
        }

        BLL.BLLSanPham.HienThiSanPham(tblSanPham);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        BLL.BLLSanPham.HienThiSanPhamTimKiem(tblSanPham, txttimkiem.getText());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txttimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttimkiemActionPerformed

    }//GEN-LAST:event_txttimkiemActionPerformed


    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        BLL.BLLSanPham.HienThiSanPham(tblSanPham);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        BLL.BLLKho.HienThiKho(tblKho, txtTimKiemKho.getText());
    }//GEN-LAST:event_btnTimKiemActionPerformed
       public void clickrun(){
          
              DefaultTableModel model = (DefaultTableModel) tblThemThuocTinh.getModel();
    int selectedRow = tblThemThuocTinh.getSelectedRow();
       // TODO add your handling code here:
        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.images", "jpg","png");
        file.addChoosableFileFilter(filter);
        int result = file.showSaveDialog(null);
        if(result == JFileChooser.APPROVE_OPTION){
            File File  = file.getSelectedFile();
                    String path = File.getAbsolutePath();
                     JLabel lbl5 = (JLabel) model.getValueAt(selectedRow, 0);
 
               lbl5.setIcon(ResizeImage(path, null));
                ImagePast = path;
               int a = tblThemThuocTinh.getSelectedRow();
               tblThemThuocTinh.setValueAt(ImagePast, a, 8);
                 
        }else{
             System.out.println("fail");
        }
     
        
}
    private void tblThemThuocTinhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblThemThuocTinhMouseClicked
          int col = tblThemThuocTinh.columnAtPoint(evt.getPoint());
            if (col == 0)
            {
               clickrun();  
            }
             
    }//GEN-LAST:event_tblThemThuocTinhMouseClicked

    private void tblThemThuocTinhKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblThemThuocTinhKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tblThemThuocTinhKeyReleased

    private void cbkkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbkkeActionPerformed
        if (cbkke.isSelected()) {
            cbbViTriKe.setEnabled(true);
        } else {
            cbbViTriKe.setEnabled(false);
        }
    }//GEN-LAST:event_cbkkeActionPerformed

    private void bttLamMoiThuocTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttLamMoiThuocTinhActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) tblThemThuocTinh.getModel();
        dtm.setRowCount(0);
    }//GEN-LAST:event_bttLamMoiThuocTinhActionPerformed

    private void bttXoaThuocTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttXoaThuocTinhActionPerformed

        DefaultTableModel model = (DefaultTableModel) this.tblThemThuocTinh.getModel();

        int rowsCount = tblThemThuocTinh.getRowCount();
        int rows[] = tblThemThuocTinh.getSelectedRows();
        int zero = 0;

        if (rowsCount == 0) {
            ThongBaoThongTin.ThongBao("Bảng không có thuộc tính", "Thông báo");
        } else {
            if (rows.length < 1) {
                ThongBaoThongTin.ThongBao("Vui lòng chọn dòng cần xóa", "Thông báo");
            } else {
                for (int i = 0; i < rows.length; i++) {
                    model.removeRow(rows[i] - i);
                }
            }
        }
    }//GEN-LAST:event_bttXoaThuocTinhActionPerformed
  public static class mytable implements TableCellRenderer {

        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            return (Component) value;

        }
    }
    private void bttThemThuocTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttThemThuocTinhActionPerformed
        DefaultTableModel model = (DefaultTableModel) tblThemThuocTinh.getModel();
        tblThemThuocTinh.getColumnModel().getColumn(1).setCellEditor(new DefaultCellEditor(cbbsize));
        tblThemThuocTinh.getColumnModel().getColumn(2).setCellEditor(new DefaultCellEditor(cbbmau));
        Random generator = new Random();
        tblThemThuocTinh.getColumnModel().getColumn(0).setCellRenderer(new mytable()); 
            int value = generator.nextInt((99999 - 1) + 1) + 1;
             JLabel lbl2 = new JLabel("");
             
        model.addRow(new Object[]{lbl2,"Chọn size", "Chọn màu", "", "", "", "","CN"+value});
    }//GEN-LAST:event_bttThemThuocTinhActionPerformed

    private void bttZoomTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttZoomTableActionPerformed
       jdlZoomTable zoom = new jdlZoomTable(new javax.swing.JFrame(), true);
             zoom.setVisible(true);
    }//GEN-LAST:event_bttZoomTableActionPerformed

    private void bttLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttLamMoiActionPerformed
        lammoi();
    }//GEN-LAST:event_bttLamMoiActionPerformed
public boolean validCheck() {
      if(tblThemThuocTinh.getCellEditor() != null) {
         tblThemThuocTinh.getCellEditor().stopCellEditing();
      }
      for(int i=0; i < tblThemThuocTinh.getRowCount(); i++) {
         for(int j=0; j < tblThemThuocTinh.getColumnCount(); j++) {
         String value = tblThemThuocTinh.getValueAt(i,j).toString();
         if(value.trim().length() == 0) {
               return false;
            }
         }
      }
      return true;
   }
    private void bttThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttThemActionPerformed
                  if(validCheck()) {
               
            } else {
               JOptionPane.showMessageDialog(null, "Vui lòng nhập đầy đủ các thuộc tính");
            }
        int rows = tblThemThuocTinh.getRowCount();
        int kq = JOptionPane.showConfirmDialog(new JFrame(),"Xác nhận thêm sản phẩm "+"'"+txtTenSanPham.getText()+"'"+" Với "+"'"+rows+"'"+" Loại size màu",
        "Thông báo xác nhận", JOptionPane.YES_NO_OPTION);      
        if (kq == JOptionPane.YES_OPTION) {   
        for (int i = 0; i < rows; i++) {
        try { 
        String tenSP = txtTenSanPham.getText();
        String maSP = tblThemThuocTinh.getValueAt(0, 7).toString(); 
        java.sql.Date NgayNhap = new java.sql.Date(jdcNgayTao.getDate().getTime());
        String ngayTao = NgayNhap.toString();
        String thuoctinhkhachhang = cbbThuocTinhKhachHang.getSelectedItem().toString();
        String donViTinh = txtDonViTinh.getText();          
        MyCombobox mbLoaiSP = (MyCombobox) cbbLoaiSanPham.getSelectedItem();
        //chuyển đổi từ string sang int
        int loaiSP = Integer.parseInt(mbLoaiSP.Value.toString());
        //Lấy phần tử trong hàng cần chuyển đổi
         MyCombobox bmsize = (MyCombobox) tblThemThuocTinh.getValueAt(0, 1); 
        //chuyển đổi từ string sang int
        int size1 = Integer.parseInt(bmsize.Value.toString());  
        String size2 = bmsize.Text.toString();
         //Lấy phần tử trong hàng cần chuyển đổi
        MyCombobox bmmau = (MyCombobox) tblThemThuocTinh.getValueAt(0, 2);  
        int mau1 = Integer.parseInt(bmmau.Value.toString());
        String mau2 = bmmau.Text.toString();
        String khoiluong = tblThemThuocTinh.getValueAt(0, 3).toString(); 
        String giabanle = tblThemThuocTinh.getValueAt(0, 4).toString();
        String giabanbuon = tblThemThuocTinh.getValueAt(0, 5).toString();
        String gianhap = tblThemThuocTinh.getValueAt(0, 6).toString(); 
        //chọn 1 phần tử trong list combobox
        MyCombobox mbHangSP = (MyCombobox) cbbHangSanPham.getSelectedItem();
        //chuyển đổi từ string sang int
        int hangSP = Integer.parseInt(mbHangSP.Value.toString());
         //chọn 1 phần tử trong list combobox
        MyCombobox mbKe = (MyCombobox) cbbViTriKe.getSelectedItem();
        //chuyển đổi từ string sang int
        int ke = Integer.parseInt(mbKe.Value.toString());
        String moTaSp = txtMoTa.getText();        
      BLL.BLLSanPham.ThemSP((tenSP), ngayTao, moTaSp, maSP, giabanle, giabanbuon, gianhap, khoiluong, donViTinh, loaiSP, hangSP, thuoctinhkhachhang, size1, mau1, ke);      
            ((DefaultTableModel)tblThemThuocTinh.getModel()).removeRow(0);
        }  catch (ArrayIndexOutOfBoundsException ex){
             ThongBaoCanhBao.ThongBao("Hết hàng", "Thông báo");
        }
            }
           ThongBaoThongTin.ThongBao("Thêm thành công "+"'"+txtTenSanPham.getText()+"'"+" Và "+"'"+rows+"'"+" Loại size màu", "Thông báo");
              BLL.BLLSanPham.HienThiSanPham(tblSanPham);
              tbpchuyentab.setSelectedIndex(0);
            }
        
        
        
        
        
        
        
    }//GEN-LAST:event_bttThemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton bttLamMoi;
    private javax.swing.JButton bttLamMoiThuocTinh;
    private javax.swing.JButton bttThem;
    private javax.swing.JButton bttThemThuocTinh;
    private javax.swing.JButton bttXoaThuocTinh;
    private javax.swing.JButton bttZoomTable;
    private javax.swing.JComboBox<String> cbbHangSanPham;
    public static javax.swing.JComboBox<String> cbbLoaiSanPham;
    private javax.swing.JComboBox<String> cbbThuocTinhKhachHang;
    private javax.swing.JComboBox<String> cbbViTriKe;
    private javax.swing.JCheckBox cbkke;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    public static javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel58;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel87;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane3;
    public static javax.swing.JScrollPane jScrollPaneSanPham;
    private com.toedter.calendar.JDateChooser jdcNgayTao;
    private javax.swing.JLabel lblLink;
    public static javax.swing.JLabel lblNull;
    private javax.swing.JLabel lblTenAnh;
    private javax.swing.JLabel lbthongtincoban1;
    private javax.swing.JPanel pnldanhsach;
    private javax.swing.JScrollPane srcdanhsach;
    private javax.swing.JScrollPane srcdanhsach2;
    public static javax.swing.JTable tblKho;
    public static javax.swing.JTable tblSanPham;
    public static javax.swing.JTable tblThemThuocTinh;
    private javax.swing.JTabbedPane tbpchuyentab;
    private javax.swing.JTextField txtDonViTinh;
    private javax.swing.JTextField txtIDSanPham;
    private javax.swing.JTextArea txtMoTa;
    private javax.swing.JTextField txtTenSanPham;
    private javax.swing.JTextField txtTimKiemKho;
    public static javax.swing.JTextField txtidsanpham;
    private javax.swing.JTextField txttimkiem;
    // End of variables declaration//GEN-END:variables
}
